import localFont from "next/font/local";
import "../../globals.css";
import DashboardHeader from "@/app/Components/Dashboard/DashboardHeader";
import Sidebar from "@/app/Components/Dashboard/Sidebar";

const geistSans = localFont({
  src: "../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Jamaate-islami Admin Dashboard",
  description: "Generated by create next app",
};

export default function DashboardRootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
           w-full h-screen overflow-hidden
        `}
      >
        {/*  Main Wrapper */}

        <DashboardHeader />
        <div className=" flex">
          <aside>
            <Sidebar />
          </aside>
          <main className=" flex-1 h-screen overflow-y-scroll p-4 bg-green-50">
            {children}
            <div style={{ height: "1000px" }}></div>
          </main>
        </div>

      </body>
    </html>
  );
}
